$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: taxi-training-pipeline
description: Training Pipeline to train a model that predicts taxi fare price

# <inputs_and_outputs>
inputs:
  input:
    type: uri_file
    path: azureml:taxi-data@latest
  enable_monitoring: "false"
  table_name: 'taximonitoring'

outputs: 
  train_data:
  val_data:
  test_data:
  trained_model:
  evaluation_output:
  model_info_output_path:
# </inputs_and_outputs>

# <jobs>
settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cpu-cluster2
  continue_on_step_failure: false

jobs:
  prep_data:
    component: ../../../components/prep.yml
    
    inputs:
      raw_data: ${{parent.inputs.input}}
      enable_monitoring: ${{parent.inputs.enable_monitoring}}
      table_name: ${{parent.inputs.table_name}}
    outputs:
      train_data: ${{parent.outputs.train_data}}
      val_data: ${{parent.outputs.val_data}}
      test_data: ${{parent.outputs.test_data}}

  train_model:
    component: ../../../components/train.yml
   
    inputs:
      train_data: ${{parent.jobs.prep_data.outputs.train_data}}
    outputs:
      model_output: ${{parent.outputs.trained_model}}
  
  evaluate_model:
    component: ../../../components/evaluate.yml
   
    inputs:
      model_name: "taxi-model"
      model_input: ${{parent.jobs.train_model.outputs.model_output}}
      test_data: ${{parent.jobs.prep_data.outputs.test_data}}
    outputs:
      evaluation_output: ${{parent.outputs.evaluation_output}}

  register_model:
    component: ../../../components/register.yml
    
    inputs:
      model_name: "taxi-model"
      model_path: ${{parent.jobs.train_model.outputs.model_output}}
      evaluation_output: ${{parent.jobs.evaluate_model.outputs.evaluation_output}}
    outputs:
      model_info_output_path: ${{parent.outputs.model_info_output_path}}
# </jobs>