# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Prod environment
variables:
  # Global
  ap_vm_image: ubuntu-20.04

  namespace: gasunimlopsv2 
  location: westeurope
  environment: prod
  enable_aml_computecluster: true
  enable_monitoring: false
  random_suffix: 8a6

  # Azure DevOps
  ado_service_connection_rg: gasuni-mlopsv2-rg-sc-prod
  ado_service_connection_aml_ws: sc-su-gu-sbx-ms-aml-ws

  # DO NOT TOUCH

  # For pipeline reference
  resource_group: rg-$(namespace)-$(environment)
  aml_workspace: mlw-$(namespace)-$(environment)
  application_insights: mlw$(namespace)$(environment)$(random_suffix)
  key_vault: kv$(namespace)$(environment)$(random_suffix)
  container_registry: cr$(namespace)$(environment)$(random_suffix)
  storage_account: st$(namespace)$(environment)$(random_suffix)


  # For terraform reference
  terraform_version: 1.3.6
  terraform_workingdir: infrastructure
  terraform_st_location: $(location)
  terraform_st_resource_group: rg-$(namespace)-$(environment)-tf
  terraform_st_storage_account: st$(namespace)-$(environment)tf
  terraform_st_container_name: default
  terraform_st_key: mlops-tab
