
# Azure Pipelines YAML for training the SDK

name: deploy-model-training-pipeline

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'prod') }}:
      - template: ../config-infra-prod.yml
      - group: ProdVars
  - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
      - template: ../config-infra-dev.yml
      - group: DevVars

  - name: version
    value: python-sdk-v2

pool:
  name: Self-hosted Agents
  vmImage: windows-latest



steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
- script: pip install -r ci-cd/azure-pipelines/dev-requirements.txt
  displayName: 'pip install notebook reqs'
- task: Bash@3
  inputs:
    filePath: 'ci-cd/azure-pipelines/setup-sdk.sh'
  displayName: 'set up sdk'

- task: Bash@3
  inputs:
    filePath: 'ci-cd/azure-pipelines/setup-cli.sh'
  displayName: 'set up CLI'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azureml-mldemo' #name of the AzureML service connection defined in Azure Pipelines
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
           sed -i -e "s/DefaultAzureCredential/AzureCliCredential/g" train-sdkv2.ipynb
           papermill -k python train-sdkv2.ipynb train-sdkv2.output.ipynb
    workingDirectory: 'ml-pipelines/sdk'